/**
 * Every user-facing string lives here, not inline in JSX. The UI is Russian
 * only and there is no i18n library — keeping them in one module means adding
 * a second language later is a swap, not a rewrite.
 */
export const strings = {
  appName: 'Семейные финансы',

  nav: {
    dashboard: 'Обзор',
    accounts: 'Счета',
    transactions: 'Операции',
    budgets: 'Бюджеты',
    goals: 'Цели',
    bills: 'Платежи',
    categories: 'Категории',
    topics: 'События',
    password: 'Смена пароля',
    users: 'Пользователи',
    logout: 'Выйти',
  },

  login: {
    title: 'Вход',
    email: 'Электронная почта',
    password: 'Пароль',
    submit: 'Войти',
    submitting: 'Вход…',
    invalidCredentials: 'Неверная почта или пароль',
  },

  common: {
    loading: 'Загрузка…',
    save: 'Сохранить',
    cancel: 'Отмена',
    delete: 'Удалить',
    edit: 'Изменить',
    add: 'Добавить',
    confirm: 'Подтвердить',
    retry: 'Повторить',
    /** Shown when a transaction points at a soft-deleted account. */
    deletedAccount: 'Удалённый счёт',
    /** Summary rows with no category. */
    uncategorized: 'Без категории',
    error: 'Не удалось выполнить запрос',
    empty: 'Пока ничего нет',
  },

  dashboard: {
    income: 'Доходы',
    expense: 'Расходы',
    net: 'Итого',
    spent: 'Потрачено',
    spendingByCategory: 'Расходы по категориям',
    accounts: 'Счета',
    budgets: 'Бюджеты за месяц',
    billsDue: 'Ближайшие платежи',
    nothingDue: 'Ничего не ожидается',
    allCaughtUp: 'Просроченных платежей нет',
  },

  categories: {
    title: 'Категории',
    add: 'Добавить категорию',
    addTitle: 'Новая категория',
    addChild: 'Добавить подкатегорию',
    editTitle: 'Изменить категорию',
    name: 'Название',
    kind: 'Тип',
    kinds: { EXPENSE: 'Расход', INCOME: 'Доход' },
    /** Fixed at creation — a category's kind decides where it can be used. */
    kindHint: 'Тип нельзя изменить после создания',
    parent: 'Родительская категория',
    noParent: 'Без родителя',
    created: 'Категория создана',
    updated: 'Категория изменена',
    deleted: 'Категория удалена',
    deleteTitle: 'Удалить категорию?',
    /** History keeps pointing at it; only new use is prevented. */
    deleteHint: 'Прошлые операции сохранят её название — она исчезнет только из списков выбора',
    /** Both blocks come back as 409. */
    blockedByChildren: 'Сначала удалите или перенесите подкатегории',
    blockedByBudget: 'Категорию использует активный бюджет',
    empty: 'Категорий пока нет',
  },

  password: {
    title: 'Смена пароля',
    current: 'Текущий пароль',
    next: 'Новый пароль',
    repeat: 'Повторите новый пароль',
    submit: 'Сменить пароль',
    mismatch: 'Пароли не совпадают',
    tooShort: 'Не меньше 8 символов',
    /** The change invalidates the token making the call. */
    hint: 'После смены пароля все сеансы завершатся — потребуется войти заново',
    done: 'Пароль изменён. Войдите заново',
  },

  users: {
    title: 'Пользователи',
    add: 'Создать пользователя',
    email: 'Электронная почта',
    displayName: 'Имя',
    password: 'Пароль',
    /** The endpoint can only create MEMBER; OWNER is rejected. */
    roleHint: 'Новый пользователь получает роль «Член семьи»',
    /** There is no list endpoint — the screen is create-only by design. */
    noList: 'Список пользователей недоступен — можно только создать нового',
    created: 'Пользователь создан',
  },

  accounts: {
    title: 'Счета',
    balance: 'Баланс',
    type: 'Тип',
    bank: 'Банк',
    reconcile: 'Сверить баланс',
    reconcileTitle: 'Сверка баланса',
    actualBalance: 'Фактический баланс',
    currentBalance: 'Баланс в системе',
    difference: 'Разница',
    /** The adjustment is a ledger row, not a silent balance edit. */
    reconcileHint: 'Будет создана операция-корректировка на разницу',
    reconcileNoChange: 'Баланс уже совпадает — корректировка не нужна',
    reconciled: 'Баланс скорректирован',
    history: 'История операций',
    notFound: 'Счёт не найден',
    /** Negative is legal — a signal that something is missing, not an error. */
    negativeHint: 'Баланс отрицательный. Возможно, не внесена какая-то операция — сверьте баланс.',
    noBank: 'Без банка',
    name: 'Название',
    currency: 'Валюта',
    openingBalance: 'Начальный баланс',
    addTitle: 'Новый счёт',
    add: 'Добавить счёт',
    editTitle: 'Изменить счёт',
    /** Only name and bank are patchable. */
    editHint: 'Тип, валюту и баланс изменить нельзя — баланс меняется операциями и сверкой',
    created: 'Счёт создан',
    updated: 'Счёт изменён',
    bankSearch: 'Найти или добавить банк',
    bankNotFound: 'Банк не найден',
    bankCreate: 'Добавить',
    types: {
      CASH: 'Наличные',
      BANK: 'Банковский счёт',
      DEPOSIT: 'Депозит',
      BROKER: 'Брокерский счёт',
    },
  },

  transactions: {
    title: 'Операции',
    types: {
      INCOME: 'Доход',
      EXPENSE: 'Расход',
      TRANSFER: 'Перевод',
      ADJUSTMENT: 'Корректировка',
    },
    /** Deleting reverses the balance, so the dialog says so explicitly. */
    deleteWarning: 'Баланс счёта будет пересчитан. Отменить это действие нельзя.',
    from: 'С',
    to: 'По',
    account: 'Счёт',
    category: 'Категория',
    date: 'Дата',
    amount: 'Сумма',
    note: 'Заметка',
    allAccounts: 'Все счета',
    allCategories: 'Все категории',
    /** The API caps the window at a year and 400s past it. */
    rangeTooLong: 'Диапазон не может превышать один год',
    rangeInverted: 'Дата начала позже даты окончания',
    noneInRange: 'За выбранный период операций нет',
    addTitle: 'Новая операция',
    add: 'Добавить операцию',
    type: 'Тип',
    fromAccount: 'Счёт списания',
    toAccount: 'Счёт зачисления',
    toAmount: 'Сумма зачисления',
    exchangeRate: 'Курс к тенге',
    /** Shown under the rate input so the direction is unambiguous. */
    exchangeRateHint: 'Сколько тенге за 1 единицу валюты счёта',
    noCategory: 'Без категории',
    saved: 'Операция сохранена',
    editTitle: 'Изменить операцию',
    updated: 'Операция изменена',
    deleteTitle: 'Удалить операцию?',
    deleted: 'Операция удалена',
    /** Type and both accounts are immutable on PATCH. */
    immutableHint: 'Тип и счета изменить нельзя — удалите операцию и создайте заново',
    /** The two sides of a cross-currency transfer must travel together. */
    crossCurrencyHint: 'Обе суммы отправляются вместе, иначе стороны перевода разойдутся',
    errors: {
      amountPositive: 'Сумма должна быть больше нуля',
      amountInvalid: 'Введите сумму числом',
      accountRequired: 'Выберите счёт',
      toAccountRequired: 'Выберите счёт зачисления',
      toAccountSame: 'Счета должны быть разными',
      toAmountRequired: 'Укажите сумму зачисления — валюты счетов различаются',
      exchangeRateRequired: 'Укажите курс — счёт не в тенге',
      dateFuture: 'Дата не может быть в будущем',
      noteTooLong: 'Не больше 1000 символов',
    },
  },

  budgets: {
    title: 'Бюджеты',
    limit: 'Лимит',
    spent: 'Потрачено',
    remaining: 'Остаток',
    /** An empty month is normal, not a missing-configuration state. */
    noneThisMonth: 'В этом месяце бюджетов не было',
    add: 'Добавить бюджет',
    addTitle: 'Новый бюджет',
    editTitle: 'Изменить бюджет',
    alertThreshold: 'Порог предупреждения, %',
    /** Nothing alerts — the threshold only colours the bar. */
    alertThresholdHint: 'Только цвет полосы — уведомления не отправляются',
    /** A limit change applies from the current month, leaving history intact. */
    editHint: 'Новый лимит действует с текущего месяца, прошлые месяцы сохранят прежний',
    deleteTitle: 'Удалить бюджет?',
    deleteHint: 'Бюджет перестанет действовать с текущего месяца, прошлые месяцы сохранят его',
    created: 'Бюджет создан',
    updated: 'Бюджет изменён',
    deleted: 'Бюджет удалён',
    duplicate: 'Для этой категории уже есть бюджет',
    usageVsLimit: 'Расход и лимит',
    /** Only EXPENSE categories can be budgeted. */
    expenseOnly: 'Бюджет можно завести только для категории расходов',
  },

  goals: {
    title: 'Цели',
    target: 'Цель',
    contribute: 'Пополнить',
    achieved: 'Достигнута',
    statuses: {
      ACTIVE: 'Активная',
      ABANDONED: 'Отменённая',
      ARCHIVED: 'В архиве',
    },
    types: {
      SAVINGS: 'Накопления',
      EMERGENCY_FUND: 'Подушка безопасности',
    },
    add: 'Добавить цель',
    addTitle: 'Новая цель',
    editTitle: 'Изменить цель',
    name: 'Название',
    targetAmount: 'Целевая сумма',
    targetDate: 'Срок',
    noTargetDate: 'Без срока',
    linkedAccount: 'Счёт',
    /** Fixed after creation: progress is measured against it. */
    linkedAccountHint: 'Счёт нельзя изменить после создания — прогресс считается по его балансу',
    status: 'Статус',
    showAll: 'Показать все',
    showActive: 'Только активные',
    onlyActiveEmpty: 'Активных целей нет',
    created: 'Цель создана',
    updated: 'Цель изменена',
    deleted: 'Цель удалена',
    deleteTitle: 'Удалить цель?',
    /** Progress is derived from the account balance, so nothing else is lost. */
    deleteHint: 'Операции по счёту останутся — удаляется только сама цель',
    /** Contributing is an ordinary transaction, not a separate endpoint. */
    contributeHint: 'Пополнение — обычный перевод на связанный счёт',
  },

  topics: {
    title: 'События',
    /** «Тема» is the literal translation but reads oddly for a trip. */
    one: 'Событие',
    add: 'Добавить событие',
    addTitle: 'Новое событие',
    editTitle: 'Изменить событие',
    name: 'Название',
    description: 'Описание',
    startDate: 'Начало',
    endDate: 'Окончание',
    plannedAmount: 'Планируемая сумма',
    /** Display only — nothing alerts and nothing blocks. */
    plannedHint: 'Только для сравнения — ограничений не накладывает',
    spent: 'Потрачено',
    received: 'Возвраты',
    net: 'Итого',
    remaining: 'Остаток',
    planned: 'План',
    transactionCount: 'Операций',
    /** The real span can start before the declared window. */
    actualSpan: 'Фактический период',
    declaredSpan: 'Заявленный период',
    noDates: 'Период не указан',
    statuses: { ACTIVE: 'Активное', CLOSED: 'Закрытое' },
    showAll: 'Показать все',
    showActive: 'Только активные',
    onlyActiveEmpty: 'Активных событий нет',
    created: 'Событие создано',
    updated: 'Событие изменено',
    deleted: 'Событие удалено',
    deleteTitle: 'Удалить событие?',
    /** A topic is a view; deleting it must not delete money. */
    deleteHint: 'Операции останутся в журнале — удаляется только само событие',
    duplicate: 'Событие с таким названием уже есть',
    attached: 'Операции добавлены',
    detached: 'Операция откреплена',
    detach: 'Открепить',
    attach: 'Добавить операции',
    attachTitle: 'Добавить операции в событие',
    /** Candidates are a suggestion, never an action. */
    candidatesHint: 'Показаны неприкреплённые операции за указанный период — проверьте каждую',
    candidatesNeedDates: 'Укажите даты события, чтобы подобрать операции',
    noCandidates: 'Подходящих операций нет',
    selected: 'Выбрано',
    noTransactions: 'В событии пока нет операций',
    noTopic: 'Без события',
    topicField: 'Событие',
    allTopics: 'Все события',
  },

  bills: {
    title: 'Платежи',
    dueDate: 'Срок',
    overdue: 'Просрочен',
    paid: 'Оплачен',
    markPaid: 'Отметить оплаченным',
    /** Marking paid does not create a transaction. */
    markPaidHint: 'Операция в журнале не создаётся — внесите её отдельно',
    unpaidPanel: 'К оплате',
    deleteSeries: 'Удалить всю серию',
    add: 'Добавить платёж',
    addTitle: 'Новый платёж',
    editTitle: 'Изменить платёж',
    batchAdd: 'Создать серию',
    batchTitle: 'Регулярный платёж',
    name: 'Название',
    amount: 'Сумма',
    currency: 'Валюта',
    dayOfMonth: 'День месяца',
    startMonth: 'С месяца',
    endMonth: 'По месяц',
    preview: 'Будет создано',
    /** Day 31 in a short month lands on its last day. */
    clampHint: 'В коротких месяцах дата переносится на последний день',
    tooManyRows: 'Слишком длинный период — не больше 120 платежей за раз',
    invalidRange: 'Начальный месяц позже конечного',
    created: 'Платёж создан',
    batchCreated: 'Серия создана',
    updated: 'Платёж изменён',
    deleted: 'Платёж удалён',
    seriesDeleted: 'Серия удалена',
    deleteTitle: 'Удалить платёж?',
    deleteSeriesTitle: 'Удалить всю серию?',
    deleteSeriesHint: 'Будут удалены все платежи, созданные вместе с этим',
    markUnpaid: 'Снять отметку',
    calendar: 'Календарь',
    noneThisMonth: 'В этом месяце платежей нет',
    nothingUnpaid: 'Всё оплачено',
    weekdays: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
  },
} as const
